export const GET_HOSPITAL_DATA = "GET_HOSPITAL_DATA";
export const GET_TAGS_DATA = "GET_TAGS_DATA";
export const UPDATE_INVENTORY_ITEM_COUNT = "UPDATE_INVENTORY_ITEM_COUNT";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
